kafka-lag-exporter {
  reporters.prometheus.port = 9999
  clusters = [
    {
      name = "taxi-kraft"
      bootstrap-brokers = "kafka1:29092,kafka2:29092,kafka3:29092"
      consumer-properties = {
        client.id = "kafka-lag-exporter"
      }
    }
  ]
  poll-interval = 15 seconds
}
